# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 3D Reconstruction of Shoulder Muscles in Hominoid Primates - Code content
author: Julia van Beesel
logo: MuscleReconstructions.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force


# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  hide-code: true

# Jupyter-specific settings
jupyter:
  hide-code: true